{"name": "test_perform_authorization_on_github", "status": "failed", "statusDetails": {"message": "AssertionError: Authorization failed: User is not found\nassert 'login' in {'documentation_url': 'https://docs.github.com/rest', 'message': 'Bad credentials'}\n +  where {'documentation_url': 'https://docs.github.com/rest', 'message': 'Bad credentials'} = <bound method Apiresponses.get_json of <api.api_responses.Apiresponses object at 0x000001B77FA9A350>>()\n +    where <bound method Apiresponses.get_json of <api.api_responses.Apiresponses object at 0x000001B77FA9A350>> = <api.api_responses.Apiresponses object at 0x000001B77FA9A350>.get_json", "trace": "@pytest.mark.tryfirst\n    def test_perform_authorization_on_github():\n        response = api.send_get(read_user_endpoint(), auth=auth)\n        authorization_response = Apiresponses(response)\n        print(authorization_response.get_status_code())\n        print(authorization_response.get_content())\n    \n>       assert \"login\" in authorization_response.get_json(), \"Authorization failed: User is not found\"\nE       AssertionError: Authorization failed: User is not found\nE       assert 'login' in {'documentation_url': 'https://docs.github.com/rest', 'message': 'Bad credentials'}\nE        +  where {'documentation_url': 'https://docs.github.com/rest', 'message': 'Bad credentials'} = <bound method Apiresponses.get_json of <api.api_responses.Apiresponses object at 0x000001B77FA9A350>>()\nE        +    where <bound method Apiresponses.get_json of <api.api_responses.Apiresponses object at 0x000001B77FA9A350>> = <api.api_responses.Apiresponses object at 0x000001B77FA9A350>.get_json\n\ntest_all_together.py:32: AssertionError"}, "attachments": [{"name": "stdout", "source": "f5e63014-a161-42e7-8d88-7096f9bfa1f4-attachment.txt", "type": "text/plain"}], "start": 1679227575718, "stop": 1679227575970, "uuid": "008ea994-511f-4c04-8caa-73fb27100df4", "historyId": "80e88ba2adeb14f21da3e50f09777f8f", "testCaseId": "71fc255bb31d5ae9523c891479c68856", "fullName": "test_all_together#test_perform_authorization_on_github", "labels": [{"name": "tag", "value": "@pytest.mark.tryfirst"}, {"name": "suite", "value": "test_all_together"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "2344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_all_together"}]}