{"name": "test_create_new_pr", "status": "failed", "statusDetails": {"message": "AssertionError: assert 422 == 201\n +  where 422 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002284169ACE0>>()\n +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002284169ACE0>> = <api.api_responses.Apiresponses object at 0x000002284169ACE0>.get_status_code", "trace": "def test_create_new_pr():\n        response = api.send_post(pulls, auth=auth, json=params)\n        pr_create_response = Apiresponses(response)\n>       assert pr_create_response.get_status_code() == 201\nE       assert 422 == 201\nE        +  where 422 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002284169ACE0>>()\nE        +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x000002284169ACE0>> = <api.api_responses.Apiresponses object at 0x000002284169ACE0>.get_status_code\n\ntest_all_together.py:60: AssertionError"}, "start": 1679222263249, "stop": 1679222263668, "uuid": "0bd11543-e418-42d3-84df-e60b5036064c", "historyId": "41b560b1a59af6565535d677d61eb1b3", "testCaseId": "0b820b48968caf55db6ab716d7810690", "fullName": "test_all_together#test_create_new_pr", "labels": [{"name": "suite", "value": "test_all_together"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "5504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_all_together"}]}