{"name": "test_create_new_pr", "status": "failed", "statusDetails": {"message": "AssertionError: assert 401 == 201\n +  where 401 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x00000197621E0460>>()\n +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x00000197621E0460>> = <api.api_responses.Apiresponses object at 0x00000197621E0460>.get_status_code", "trace": "def test_create_new_pr():\n        api = Apirequests(read_base_url())\n        response = api.send_post(pulls, auth=auth, json=params)\n        pr_create_response = Apiresponses(response)\n>       assert pr_create_response.get_status_code() == 201\nE       assert 401 == 201\nE        +  where 401 = <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x00000197621E0460>>()\nE        +    where <bound method Apiresponses.get_status_code of <api.api_responses.Apiresponses object at 0x00000197621E0460>> = <api.api_responses.Apiresponses object at 0x00000197621E0460>.get_status_code\n\ntest_creation_of_pullrequest.py:16: AssertionError"}, "start": 1679227480819, "stop": 1679227481079, "uuid": "e93330fc-e048-4d23-b03e-090a86166fdd", "historyId": "c291b1acbda530a8b2583d7c04fd5449", "testCaseId": "79adebac2b71d015c39857b386ab34ec", "fullName": "test_creation_of_pullrequest#test_create_new_pr", "labels": [{"name": "suite", "value": "test_creation_of_pullrequest"}, {"name": "host", "value": "AlphaTest"}, {"name": "thread", "value": "13220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_creation_of_pullrequest"}]}